name: pomodoro
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  permission_handler: 
  shared_preferences: ^2.4.0
  flutter_colorpicker: ^1.1.0
  just_audio: ^0.9.18


dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true 
  ios: false    
  image_path: "assets/logo/logo.png" 

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
